version: '3.8'

services:
  cut-roll-identity:
    image: makedoniaz/cut-roll-identity:latest
    build:
      context: .
      dockerfile: app.Dockerfile
    container_name: identity_container
    environment:
      ASPNETCORE_URLS: "http://+:80" 

      POSTGRES_CONNECTION_STRING: "Host=${POSTGRES_HOST};Port=${POSTGRES_PORT};Username=${POSTGRES_USER};Password=${POSTGRES_PASSWORD};Database=${POSTGRES_DB};Pooling=true;"
      BLOB_STORAGE_CONNECTION_STRING: "DefaultEndpointsProtocol=${AZURE_BLOB_DEFAULT_PROTOCOL};AccountName=${AZURE_BLOB_ACCOUNT_NAME};AccountKey=${AZURE_BLOB_ACCOUNT_KEY};EndpointSuffix=${AZURE_BLOB_ENDPOINT_SUFFIX}"

      JWT_KEY: "${JWT_KEY}"
      JWT_LIFE_TIME_IN_MINUTES: "15"
      JWT_ISSUER: "${JWT_ISSUER}"
      JWT_AUDIENCE: "${JWT_AUDIENCE}"
      RABBIT_MQ_HOSTNAME: "${RABBIT_MQ_HOSTNAME}"
      RABBIT_MQ_USERNAME: "${RABBIT_MQ_USERNAME}"
      RABBIT_MQ_PASSWORD: "${RABBIT_MQ_PASSWORD}"
      DEFAULT_ADMIN_USERNAME: "${DEFAULT_ADMIN_USERNAME}"
      DEFAULT_ADMIN_EMAIL: "${DEFAULT_ADMIN_EMAIL}"
      DEFAULT_ADMIN_PASSWORD: "${DEFAULT_ADMIN_PASSWORD}"
      EMAIL_PORT: "${EMAIL_PORT}"
      EMAIL_SERVER: "${EMAIL_SERVER}"
      EMAIL_USER: "${EMAIL_USER}"
      EMAIL_EMAIL: "${EMAIL_EMAIL}"
      EMAIL_NAME: "${EMAIL_NAME}"
      EMAIL_PASSWORD: "${EMAIL_PASSWORD}"
      GOOGLE_OAUTH_CLIENT_ID: "${GOOGLE_OAUTH_CLIENT_ID}"
      GOOGLE_OAUTH_CLIENT_SECRET: "${GOOGLE_OAUTH_CLIENT_SECRET}"
      GOOGLE_OAUTH_CALLBACK_PATH: "${GOOGLE_OAUTH_CALLBACK_PATH}"
      REDIRECT_SCHEME: "${REDIRECT_SCHEME}"
      REDIRECT_HOST: "${REDIRECT_HOST}"
      REDIRECT_PORT: "${REDIRECT_PORT}"
      REDIRECT_PATH: "${REDIRECT_PATH}"
      ACME_EMAIL: "${ACME_EMAIL}"
      IDENTITY_HOST: "${IDENTITY_HOST}"
      ASPNETCORE_ENVIRONMENT: "${ASPNETCORE_ENVIRONMENT}"

    depends_on:
      - postgres-identity
    networks:
      - microservices-network
      - web
    restart: always
    ports:
      - "${LOCAL_IDENTITY_PORT}:80"  
    labels:
      - "traefik.enable=${TRAEFIK_ENABLED}" 
      - "traefik.http.routers.identity.rule=Host(`${DOMAIN}`) && PathPrefix(`/api/identity`)"
      - "traefik.http.routers.identity.entrypoints=websecure"
      - "traefik.http.routers.identity.tls.certresolver=myresolver"

  postgres-identity:
    image: postgres:latest
    container_name: identity_db_container
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    expose:
      - "${POSTGRES_PORT_EXT}:${POSTGRES_PORT}"
    networks:
      - microservices-network
    volumes:
      - identity_db_volume:/var/lib/postgresql/data
    restart: always

  traefik-identity:
    image: traefik:v3.0
    container_name: identity_traefik_container
    command:
      - "--providers.docker=true"
      - "--entrypoints.web.address=:80"
      - "--entrypoints.websecure.address=:443"
      - "--certificatesresolvers.myresolver.acme.httpchallenge=true"
      - "--certificatesresolvers.myresolver.acme.httpchallenge.entrypoint=web"
      - "--certificatesresolvers.myresolver.acme.email=${ACME_EMAIL}"
      - "--certificatesresolvers.myresolver.acme.storage=/letsencrypt/acme.json"
    ports:
      - "${VM_IDENTITY_PORT_HTTP}:80"    
      - "${VM_IDENTITY_PORT_HTTPS}:443"   
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock:ro"
      - "letsencrypt:/letsencrypt"
    networks:
      - web
    restart: always
    deploy:
      placement:
        constraints:
          - node.role == manager  

volumes:
  identity_db_volume:
  letsencrypt:

networks:
  microservices-network:
    external: true
  web:
    external: false
