version: '3.8'

services:
  cut-roll-identity:
    image: makedoniaz/cut-roll-identity:latest
    build:
      context: .
      dockerfile: app.Dockerfile
    container_name: identity_container
    environment:
      ASPNETCORE_URLS: "http://+:80" 
      POSTGRES_CONNECTION_STRING: "Host=${POSTGRES_HOST};Port=${POSTGRES_PORT};Username=${POSTGRES_USER};Password=${POSTGRES_PASSWORD};Database=${POSTGRES_DB};Pooling=true;"
      BLOB_STORAGE_CONNECTION_STRING: "DefaultEndpointsProtocol=${AZURE_BLOB_DEFAULT_PROTOCOL};AccountName=${AZURE_BLOB_ACCOUNT_NAME};AccountKey=${AZURE_BLOB_ACCOUNT_KEY};EndpointSuffix=${AZURE_BLOB_ENDPOINT_SUFFIX}"
      JWT_KEY: "${JWT_KEY}"
      JWT_LIFE_TIME_IN_MINUTES: "15"
      JWT_ISSUER: "${JWT_ISSUER}"
      JWT_AUDIENCE: "${JWT_AUDIENCE}"
      RABBIT_MQ_HOSTNAME: "${RABBIT_MQ_HOSTNAME}"
      RABBIT_MQ_USERNAME: "${RABBIT_MQ_USERNAME}"
      RABBIT_MQ_PASSWORD: "${RABBIT_MQ_PASSWORD}"
      DEFAULT_ADMIN_USERNAME: "${DEFAULT_ADMIN_USERNAME}"
      DEFAULT_ADMIN_EMAIL: "${DEFAULT_ADMIN_EMAIL}"
      DEFAULT_ADMIN_PASSWORD: "${DEFAULT_ADMIN_PASSWORD}"
      EMAIL_PORT: "${EMAIL_PORT}"
      EMAIL_SERVER: "${EMAIL_SERVER}"
      EMAIL_USER: "${EMAIL_USER}"
      EMAIL_EMAIL: "${EMAIL_EMAIL}"
      EMAIL_NAME: "${EMAIL_NAME}"
      EMAIL_PASSWORD: "${EMAIL_PASSWORD}"
      GOOGLE_OAUTH_CLIENT_ID: "${GOOGLE_OAUTH_CLIENT_ID}"
      GOOGLE_OAUTH_CLIENT_SECRET: "${GOOGLE_OAUTH_CLIENT_SECRET}"
      GOOGLE_OAUTH_CALLBACK_PATH: "${GOOGLE_OAUTH_CALLBACK_PATH}"
      REDIRECT_SCHEME: "${REDIRECT_SCHEME}"
      REDIRECT_HOST: "${REDIRECT_HOST}"
      REDIRECT_PORT: "${REDIRECT_PORT}"
      REDIRECT_PATH: "${REDIRECT_PATH}"
      ACME_EMAIL: "${ACME_EMAIL}"
      IDENTITY_HOST: "${IDENTITY_HOST}"
      ASPNETCORE_ENVIRONMENT: "${ASPNETCORE_ENVIRONMENT}"
    expose:
      - "80" 
    depends_on:
      - postgres-identity
    networks:
      - web
    restart: always
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.identity.rule=Host(`cutnroll.it.com`) && PathPrefix(`/api/identity`)"
      - "traefik.http.routers.identity.entrypoints=websecure"
      - "traefik.http.routers.identity.tls.certresolver=myresolver"
      - "traefik.http.services.identity.loadbalancer.server.port=80"

  postgres-identity:
    image: postgres:latest
    container_name: identity_db_container
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    networks:
      - web
    volumes:
      - identity_db_volume:/var/lib/postgresql/data
    restart: always

volumes:
  identity_db_volume:

networks:
  web:
    external: true
